Dockerfile: refactoring
Polyconseil/hound pull request #4
Opened 2017-02-20 10:01 UTC by tanyunshi

- User becomes hound
 - Add entrypoint sh to:
    - Generate keys for the container if the private key does not exist
    - Launch houndd

2017-02-21 15:08 UTC, fbochu requested changes
Pourquoi on ne part pas de l'image officielle de hound ?

2017-02-21 15:08 UTC, fbochu commented on Dockerfile
> +RUN mkdir /home/hound/.ssh /home/hound/data
tu peux utiliser `install`

2017-02-21 15:08 UTC, fbochu commented on Dockerfile
>  RUN apk update \
`apk --no-cache`

2017-02-21 15:08 UTC, fbochu commented on Dockerfile
> +	&& apk add go git openssh \
a priori, on ne veut pas garder `go`

2017-02-21 15:08 UTC, fbochu commented on Dockerfile
> +VOLUME ["/home/hound/data", "/home/hound/.ssh"]
Pourquoi la clé ne va pas dans `/data` ?

2017-02-21 15:08 UTC, fbochu commented on Dockerfile
> +RUN go install github.com/etsy/hound/cmds/houndd \
`go get`, non ?

2017-02-21 15:08 UTC, fbochu commented on run.sh
> +	echo "$FILE found."
Je ne traiterais que le cas où la clé n'existe pas

2017-02-21 15:08 UTC, fbochu commented on run.sh
> +	ssh-keygen -t rsa -b 2048 -N "" -C devops@polyconseil.fr -f $FILE -q
`devops@polyconseil.fr` -> `hound@$(hostname -f)` ?

2017-02-24 17:05 UTC, tanyunshi commented
closed

2017-02-24 17:05 UTC, closed without merging